---
title: "Task 1"
author: "Ariella Fuzaylov"
date: "4/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(survey)
library(srvyr)
```



```{r load data}
Employee_A_data=read.csv("Employee_A_data.csv", header=TRUE)
```

# Given

- $N = 40,041$
- $n = 6,000$
- SRS of $6,000$ reviews

## Subtask 1:

### Estimate average rating
```{r}
N = 40041
n= 6000
mu<-sum(Employee_A_data$Rating)/n

```
$\hat{\mu}=$ `r mu`

## Confidence interval
```{r}
srs_design = svydesign(id=~1,data=Employee_A_data, fpc=rep(N,n))

svymean(x=~Rating,design = srs_design)
conf= confint(svymean(x=~Rating,design = srs_design))
conf
```

EXPLAIN

## Subtask 2

### Calculate Mean by Branch

```{r test}
Employee_A_data%>% group_by(Branch)%>%
  summarise(n= n(), Mean= mean(Rating),StD=sd(Rating))


# Employee_A_data%>% group_by(continent)%>%summarise(n= n(), Mean= mean(Rating),StD=sd(Rating))

```

### Hypothesis Test

```{r}



```

$H_0 :$ ${\mu}_{california}={\mu}_{hongkong}={\mu}_{paris}$

$H_1 :$ ${\mu}_{california}\neq{\mu}_{hongkong}={\mu}_{paris}$